"use client";

import { useEffect, useState } from "react";

import { Suspense } from "react";

import { downloadStatement, triggerDownload } from "@/lib/api";
import { describeError } from "@/lib/errors";
import { firstOfMonthIso, todayIso } from "@/lib/money";
import { useDocumentTitle } from "@/lib/useDocumentTitle";
import { validateDateRange } from "@/lib/validation";
import type { StatementFormat } from "@/lib/types";
import { useWallet } from "@/providers/WalletProvider";
import { useToast } from "@/providers/ToastProvider";
import { PageHeader } from "@/components/AppShell";
import { Button } from "@/components/ui/Button";
import { Callout } from "@/components/ui/Callout";
import { Field, SelectField } from "@/components/ui/Field";
import { Icon } from "@/components/ui/Icon";
import { EmptyState, Panel } from "@/components/ui/Panel";
import { useSearchParams } from "next/navigation";

export default function StatementPage() {
  return (
    <Suspense fallback={<StatementSkeleton />}>
      <StatementForm />
    </Suspense>
  );
}

function StatementSkeleton() {
  return (
    <>
      <PageHeader title="Statement" description="Loading your accounts." />
      <Panel title="Download">
        <div className="space-y-4">
          <Field label="Account" value="" onChange={() => undefined} />
          <Field label="Date" value="" onChange={() => undefined} />
        </div>
      </Panel>
    </>
  );
}

function StatementForm() {
  useDocumentTitle("Statement");

  const { accounts, status } = useWallet();
  const { push } = useToast();
  const searchParams = useSearchParams();
  const requestedAccount = searchParams.get("accountId");

  const [accountId, setAccountId] = useState(requestedAccount ?? "");
  const [from, setFrom] = useState(firstOfMonthIso());
  const [to, setTo] = useState(todayIso());
  const [format, setFormat] = useState<StatementFormat>("csv");
  const [busy, setBusy] = useState(false);
  const [failure, setFailure] = useState<string | null>(null);
  const [rangeError, setRangeError] = useState<string | null>(null);

  useEffect(() => {
    if (!accountId && accounts.length > 0) setAccountId(String(accounts[0]?.id ?? ""));
  }, [accountId, accounts]);

  const download = async () => {
    const id = Number(accountId);
    if (!id) {
      setFailure("Choose the account you want a statement for.");
      return;
    }
    const errors = validateDateRange(from, to);
    const rangeMessage = errors.from ?? errors.to ?? null;
    setRangeError(rangeMessage);
    if (rangeMessage) return;

    setBusy(true);
    setFailure(null);
    try {
      const file = await downloadStatement({ accountId: id, from, to, format });
      triggerDownload(file);
      push({
        tone: "success",
        title: "Statement downloaded",
        body: `${file.filename} · ${(file.blob.size / 1024).toFixed(1)} KB`,
      });
    } catch (err) {
      setFailure(describeError(err, "Statement"));
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <PageHeader
        title="Statement"
        description="Download a period statement for one wallet. The file is generated by the service, not assembled in your browser."
      />

      {status === "loading" && accounts.length === 0 ? (
        <Panel title="Download">
          <p className="text-body text-ink-faint">Loading your accounts…</p>
        </Panel>
      ) : accounts.length === 0 ? (
        <EmptyState
          title="No accounts to statement"
          body="Open a currency wallet and this screen will have something to export."
        />
      ) : (
        <div className="space-y-5">
          <Panel title="Choose a period">
            <form
              className="space-y-5"
              onSubmit={(event) => {
                event.preventDefault();
                void download();
              }}
            >
              <div className="grid gap-5 sm:grid-cols-3">
                <SelectField
                  label="Account"
                  value={accountId}
                  onChange={setAccountId}
                  options={accounts.map((account) => ({
                    value: String(account.id),
                    label: `${account.label} (#${account.id})`,
                  }))}
                  required
                />
                <Field
                  label="From"
                  type="date"
                  value={from}
                  onChange={(value) => {
                    setFrom(value);
                    const errors = validateDateRange(value, to);
                    setRangeError(errors.from ?? errors.to ?? null);
                  }}
                  required
                />
                <Field
                  label="To"
                  type="date"
                  value={to}
                  onChange={(value) => {
                    setTo(value);
                    const errors = validateDateRange(from, value);
                    setRangeError(errors.from ?? errors.to ?? null);
                  }}
                  required
                />
              </div>

              <fieldset>
                <legend className="label mb-2">Format</legend>
                <div className="flex gap-2">
                  {(["csv", "pdf"] as const).map((option) => (
                    <label
                      key={option}
                      className={`flex-1 cursor-pointer rounded-md border px-4 py-3 text-center transition-colors sm:flex-none ${
                        format === option
                          ? "border-ink font-semibold text-ink"
                          : "border-line text-ink-muted hover:border-ink"
                      }`}
                    >
                      <input
                        type="radio"
                        name="format"
                        value={option}
                        checked={format === option}
                        onChange={() => setFormat(option)}
                        className="sr-only"
                      />
                      <span className="text-body uppercase">{option}</span>
                      <span className="mt-0.5 block text-label text-ink-faint">
                        {option === "csv" ? "Excel-ready, UTF-8 BOM" : "Printable layout"}
                      </span>
                    </label>
                  ))}
                </div>
              </fieldset>

              {rangeError ? <p className="text-label text-debit">{rangeError}</p> : null}
              {failure ? <Callout tone="error">{failure}</Callout> : null}

              <div className="flex flex-col gap-2 sm:flex-row sm:items-center">
                <Button type="submit" size="lg" loading={busy} disabled={busy || !from || !to}>
                  <Icon name="download" className="h-4 w-4" />
                  Download {format.toUpperCase()}
                </Button>
                <p className="text-label leading-5 text-ink-faint sm:ml-2">
                  Dates are inclusive and interpreted in UTC, the same way the ledger stamps them.
                </p>
              </div>
            </form>
          </Panel>

          <Panel title="Quick ranges">
            <div className="flex flex-wrap gap-2">
              {(
                [
                  { label: "This month", from: firstOfMonthIso(), to: todayIso() },
                  { label: "Last 30 days", from: shiftDays(-30), to: todayIso() },
                  { label: "Last 90 days", from: shiftDays(-90), to: todayIso() },
                ] as const
              ).map((preset) => (
                <Button
                  key={preset.label}
                  size="sm"
                  variant="secondary"
                  onClick={() => {
                    setFrom(preset.from);
                    setTo(preset.to);
                    setRangeError(null);
                  }}
                >
                  {preset.label}
                </Button>
              ))}
            </div>
          </Panel>
        </div>
      )}
    </>
  );
}

function shiftDays(days: number): string {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}
