services:
  - type: web
    name: digital-wallet-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    branch: Backend
    healthCheckPath: /api/actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
